# Generated by Django 5.2.2 on 2025-06-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='term',
            name='tags',
            field=models.ManyToManyField(to='terms.tag'),
        ),
    ]
